manuscript = """ Primary Progressive Aphasia as a Window into the Neural Architecture of Language
Maria Luisa Gorno-Tempini, Boon Lead Tee

Abstract
Primary progressive aphasia (PPA) offers a unique window into the neural organization of language and the mechanisms of neurodegeneration. This perspective article reflects on how the study of PPA—through its three core clinical variants: semantic, logopenic, and non-fluent/agrammatic—has transformed our understanding of language networks, cognitive vulnerability, and clinical-pathological correlations. Drawing from two decades of multidisciplinary research and clinical practice across Europe, Japan, and the United States, we discuss how PPA has revealed the role of large-scale brain networks in language processing and shown that distinct molecular pathologies target these networks in variant-specific ways. We also explore how factors such as language typology and developmental history may influence disease manifestation, and highlight the importance of tailored therapeutic strategies that integrate speech-language rehabilitation, biomarker-driven diagnosis, and emerging disease-modifying treatments. The perspective advocates for continued international and cross-linguistic collaboration to refine diagnostic criteria and improve care for individuals with PPA worldwide.


Early Observations and the Emergence of Primary Progressive Aphasia
Our exploration of primary progressive aphasia (PPA) began when we first encountered the concept that a neurodegenerative condition might present with isolated, progressive language deficits, rather than the memory impairments typically associated with Alzheimer's disease. This notion was groundbreaking when Marcel Mesulam in the early 1980s began to describe what we now recognize as the PPA spectrum. At that time, he worked almost exclusively with clinical observation, as technologies like MRI were far from routine and dementia was nearly synonymous with memory loss. His recognition that progressive language impairment could be the first and primary manifestation of a neurodegenerative disease was revolutionary, even though earlier historical descriptions by Pick and by Japanese researchers such as Gogi had laid some groundwork. Mesulam's hypothesis held that atrophy in these patients would likely localize to perisylvian regions in the left hemisphere, based on stroke aphasia models. Over the decades, we discovered that while much of his original thinking was correct, many patients with PPA do not have a strictly perisylvian pattern of atrophy. We also learned that PPA can be caused by pathologies other than frontotemporal lobar degeneration, including Alzheimer's disease, which may localize atypically in language networks.
As interest in PPA expanded, clinicians and scientists encountered different clinical presentations that did not entirely conform to a single model. The UK group led by John Hodges and colleagues described semantic dementia, in which fluent speech remained intact, but word comprehension and naming were severely compromised due to a deep erosion of semantic memory. This diagnosis was closely related to what Mesulam had termed fluent PPA, although the exact relationship was debated. Around the same time, Murray Grossman and coworkers introduced the concept of progressive non-fluent aphasia, which emphasized a motor speech and syntactic deficit more aligned with frontal lesions. Further complicating matters, some of these clinically distinct syndromes showed unexpectedly high frequencies of Alzheimer's disease pathology upon postmortem analysis. This finding suggested that primary progressive language syndromes could be caused by both frontotemporal lobar degeneration (FTLD) and Alzheimer's disease.
Our contribution to this evolving field included research conducted in the UK and subsequently in the United States. Following training in Italy and doctoral studies in England, we joined the University of California, San Francisco (UCSF) Memory and Aging Center, where our team conducted systematic cognitive and neuroimaging assessments of a PPA patient cohort. From these analyses emerged the logopenic variant, distinguished by specific phonological loop and lexical retrieval deficits, typically coupled with left posterior temporal and parietal atrophy. Over time, three major PPA variants were recognized: semantic, non-fluent/agrammatic, and logopenic. This tripartite classification is not entirely rigid, and healthy scientific debate continues, but it has proved helpful in linking clinical features, neuroanatomical patterns, and underlying molecular pathologies, all of which bear relevance for guiding diagnosis, prognosis, and research into future treatments.

Conceptualizing PPA Variants as Network-Based Disorders
One of the most transformative shifts in our understanding of neurodegenerative aphasias has been the recognition that these are network-based disorders. Each variant of PPA appears linked to a specific large-scale brain network with a particular "epicenter" of vulnerability. When neurodegenerative disease strikes that epicenter, it gradually spreads along established anatomical or functional connections. This network-based view has revolutionized how we map disease progression and anticipate clinical symptoms. It has also prompted new questions about why particular networks become susceptible in certain individuals.
We hypothesize that disease progression follows connectivity pathways, such that atrophy migrates from the epicenter to connected nodes, generating predictable symptom trajectories. Seminal work with resting-state functional MRI (intrinsic connectivity analyses) reveals distinct networks in healthy adults, each corresponding to specialized functions such as language, episodic memory, or socioemotional processing. Within the PPA spectrum, the left-lateralized language networks show unique susceptibility to specific protein pathologies, reflecting a complex intersection of individual developmental or genetic factors with disease-specific vulnerabilities. The resulting framework supports a model in which different tauopathies or TDP-43 pathologies preferentially target distinct connectivity networks, producing the clinical heterogeneity that defines PPA.

The Semantic Variant and Anterior Temporal Lobe Vulnerability
Among the three principal variants, the semantic variant—historically called semantic dementia—was first formally described by the UK group in the 1990s. Patients present with fluent, grammatically intact speech but have profound anomia and word comprehension difficulties. Their deficits arise from a striking loss of semantic memory, which encompasses the conceptual knowledge that allows us to recognize objects, people, and words independent of context. In everyday life, these patients struggle to name common items and understand what words mean, yet they often maintain normal articulation and syntax until later stages.
The cardinal neuroanatomical finding is bilateral atrophy of the anterior temporal lobes, often more pronounced on the left side. This corresponds well with the hypothesis that conceptual knowledge depends on distributed representations in high-level association areas, converging toward the anterior temporal lobe as a critical hub. Surface dyslexia in English is a particularly revealing symptom. Patients regularly misread irregular words because they lose the stored semantic knowledge of the specific orthography-phonology mappings, defaulting to a purely phonological decoding approach. Although surface dyslexia is best characterized in English, parallel phenomena appear in other languages, such as difficulties with kanji in Japanese, which demand the memorization of word forms rather than purely decoding phonemes.
In addition to naming and word comprehension impairments, individuals with semantic variant PPA frequently have category-level naming errors shaped by the degradation of conceptual features. They retain only the broadest features of concepts, so all animals might be misidentified as the most familiar example in that category (e.g., "dog"). As disease spreads, patients often develop more profound deficits extending beyond language: they struggle with recognition of faces (prosopagnosia), objects, or environmental sounds. Further progression can involve the right anterior temporal lobe, which frequently manifests as behavioral changes, including rigidity, reduced empathy, or compulsive behaviors. Individuals who first present with right-sided atrophy may initially come to psychiatric attention because of personality or behavioral shifts before eventually displaying word comprehension deficits when left temporal structures become more heavily involved.
Pathologically, the semantic variant is most commonly associated with frontotemporal lobar degeneration with TDP-43 inclusions (FTLD-TDP, often type C). Approximately 70% or more of semantic variant patients show TDP-43 pathology, although a small fraction can exhibit Pick's disease (a form of FTLD-tau). Rare cases can involve Alzheimer's disease, but that is the exception. This relatively consistent pathology underpins the clinical-anatomical correlation seen in the semantic variant and stands in contrast to the logopenic variant's typical association with Alzheimer's disease.

Phonological Loop Dysfunction in the Logopenic Variant
The logopenic variant PPA emerged from detailed investigations of patients at UCSF who exhibited neither the classic non-fluent/agrammatic deficits nor the key features of semantic dementia. Instead, these individuals displayed a unique pattern of hesitant speech marked by word-finding pauses, impaired sentence repetition—particularly for longer, less meaningful sentences—and phonological errors, such as substituting or mixing up sounds in complex words. Despite these expressive challenges, their motor speech articulation appeared relatively intact compared to the non-fluent variant. The primary underlying deficit implicated the phonological loop or short-term verbal memory system.
Neuroimaging localizes atrophy in the logopenic variant to the left posterior temporal and inferior parietal regions, an area strongly linked to phonological processing. Intriguingly, most of these patients exhibit Alzheimer's disease neuropathology, confirmed by biomarkers such as amyloid PET, CSF analyses, or later autopsy. This realization was pivotal, as it provided an explanation for earlier findings of seemingly "atypical" Alzheimer's pathology in some progressive aphasia patients. Rather than simply labeling them as "non-fluent" or "unclassifiable," recognizing their logopenic syndrome enabled a more accurate clinical-pathological correlation.
An especially noteworthy feature is that many logopenic variant patients have subtle or even overt histories of developmental dyslexia or familial language-based learning problems, suggesting a developmental vulnerability in the same posterior temporal-parietal network. This vulnerability does not cause Alzheimer's disease per se, but it might help explain why Alzheimer's pathology selectively impairs language networks in these individuals. Although the detailed mechanisms remain unclear, the notion of neurodevelopmental factors influencing selective localization of later neurodegenerative processes opens an intriguing line of research into lifespan approaches to brain health.
Because the posterior temporal and inferior parietal lobes intersect multiple functional domains, logopenic variant patients can display other mild symptoms, such as apraxia or dyscalculia, paralleling a Gerstmann-like syndrome. Nonetheless, the defining clinical hallmark—and the one that most severely impairs daily communication—lies in slow, hesitant speech with phonological retrieval and repetition breakdowns.

Non-Fluent/Agrammatic Variant and Its Motor Speech Spectrum
The third major variant, often called non-fluent/agrammatic, is characterized by effortful, halting speech with prominent grammatical deficits and motor speech challenges, such as apraxia of speech or dysarthria. Early descriptions, particularly from Murray Grossman's group, emphasized a primarily syntactic and morphological deficit, although subsequent work at Mayo Clinic and other centers demonstrated the key role of motor speech impairment in many patients. We now think of this variant as encompassing a spectrum, in which some individuals have pronounced apraxia of speech with relatively preserved grammar, while others have pronounced grammatical breakdown. Often these deficits eventually co-occur, reflecting a left dorsolateral frontal and insular vulnerability that compromises speech planning and production.
Neurodegeneration in the non-fluent variant often centers in the inferior frontal gyrus, premotor cortex, and supplementary motor area, with involvement of underlying white matter tracts and sometimes the basal ganglia. This localization explains why many of these patients go on to develop clinical signs consistent with corticobasal degeneration or progressive supranuclear palsy. The underlying pathology is most frequently a tauopathy (approximately 75% of cases), specifically corticobasal degeneration or Pick's disease. The remaining cases (~25%) typically exhibit TDP-43 pathology, particularly in patients with certain genetic mutations (e.g., progranulin gene mutations).
As with the other variants, language typology can shape how motor speech deficits or grammatical errors manifest clinically. In English, consonant clusters are common and readily reveal motor speech planning deficits. In contrast, in Romance languages with richer morphological systems (such as Italian) or in agglutinative languages like Japanese, the most salient linguistic deficits may manifest differently, often through morphosyntactic errors or difficulties with bound morphemes. This underscores the importance of cross-linguistic collaborations, an endeavor that we and many colleagues worldwide find increasingly crucial for improving diagnosis and care.

Progression, Network Spread, and Mixed Presentations
Although diagnostic criteria often emphasize "pure" presentations, real-world patients frequently evolve into mixed or overlapping phenotypes as disease spreads within vulnerable networks. A person who initially fits the semantic variant criteria may develop profound behavioral changes if right anterior temporal atrophy intensifies. A logopenic variant patient might eventually show signs of visuospatial or executive impairments if disease extends more dorsally. Non-fluent patients can develop widespread involvement of the basal ganglia and supplementary motor area, leading to full-blown corticobasal syndrome.
Nevertheless, a trained eye can usually detect the hallmark characteristics of each variant even after several years, at least until very advanced stages when profound cortical damage erases specific syndromic signatures. The consistent patterns of progression follow the notion that each PPA variant emerges from a large-scale connectivity network in which one region serves as the initial epicenter. Over time, the disease advances along established connections, producing gradients of atrophy and clinical decline.
The question of why a particular network becomes vulnerable to disease in an individual patient remains a significant line of investigation. Multiple factors likely contribute to this selective vulnerability, including genetic predisposition, neurodevelopmental trajectories, environmental influences, and stochastic processes. Ongoing work includes studying children of patients with familial frontotemporal dementia to identify subtle neurodevelopmental markers that could reflect future vulnerability, as well as exploring the possible intersection of typical aging processes, neuropathological protein propagation, and learning-history influences on cortical organization.

Therapeutic Approaches and the Future of PPA Care
Historically, clinicians faced limited treatment options for patients with PPA. Speech-language interventions met with skepticism among insurance providers or funding agencies who assumed that, unlike stroke, neurodegenerative conditions yield inevitable decline. Yet research from multiple centers confirms that targeted speech therapy can sustain or even improve language performance, especially when tailored to each patient's variant-specific deficits and potential strengths in unaffected networks. The phonological approach might be leveraged for semantic variant patients who rely on a relatively intact dorsal stream, while emphasis on lexical retrieval training and strategic use of preserved semantic knowledge can benefit those with logopenic or non-fluent deficits. Evidence also supports the use of teletherapy, which broadens access to specialized care for a wider population, and non-invasive brain stimulation paired with speech therapy shows promise for bolstering adaptive reorganization within partially intact language networks.
Pharmacological trials aimed at PPA are becoming more common. For logopenic variant patients, who typically have Alzheimer's pathology, emerging anti-amyloid and anti-tau treatments open new possibilities if started early, before extensive cortical damage accumulates. For FTLD-related PPA variants, innovative tau-directed therapies, progranulin gene therapies, or other disease-modifying strategies have entered clinical testing. Even if these therapies only modestly slow progression, the additional benefits of speech and cognitive retraining could extend independence and improve quality of life for individuals whose prime difficulty lies in communication.
We have come to appreciate the necessity of bridging basic and clinical research in advancing PPA care. Clinically, we strive to develop improved diagnostic protocols, identify biomarkers for pathology, and personalize treatments. Simultaneously, we use advanced neuroimaging techniques to map functional connectivity, highlight changes in network dynamics, and uncover how certain developmental vulnerabilities predispose individuals to atypical Alzheimer's or frontotemporal pathologies. This unification of theoretical neuroscience with pragmatic care is particularly relevant when we consider the cost, time, and effort required to recruit, follow, and study patients with atypical degenerative presentations.
In recent years, our laboratory and others have moved beyond documenting deficits to exploring positive or compensatory phenomena in PPA. Patients with semantic variant PPA might develop heightened reliance on phonological or visuospatial skills. Some individuals display new artistic or musical talents, suggesting that the reorganization of one brain network can sometimes release creative potential or shift cognitive resources in unexpected ways. Incorporating this perspective into therapy could yield innovative strategies that harness remaining or even newly enhanced abilities.
We are on the cusp of potentially transformative years for PPA research and care. The field has reached a level of consensus on the major variant classifications, while still recognizing the complexity and heterogeneity of real-world cases. Disease-modifying therapies, particularly those targeting Alzheimer's pathology, may shift the landscape for the logopenic variant, even as tau- and TDP-focused treatments advance for the non-fluent/agrammatic and semantic variants. With better biomarker tools, earlier recognition of subtle language changes, and cross-linguistic diagnostic criteria, clinicians can diagnose PPA variants more precisely and enroll patients in targeted treatments before extensive tissue loss occurs.
Equally important is maintaining a holistic view of patient and caregiver experiences. PPA robs individuals of one of their most vital faculties: the ability to communicate fluidly. This impairment has implications for emotional well-being, social identity, and even safety in daily activities. Families and caregivers often bear the burden of decoding cryptic speech or assisting with basic tasks that require verbal proficiency. By combining pharmacological interventions with linguistically informed speech therapy and psychosocial support, we move closer to a truly person-centered model of care. The collaborative ethos that has defined the PPA field—from early champions like Mesulam, Hodges, and Grossman, to younger investigators expanding our knowledge into multiple languages and cultural contexts—remains vital. By uniting our efforts and sharing data, knowledge, and intervention strategies, we can accelerate progress toward more effective treatments and improved patient outcomes.

Cross-Linguistic Research in PPA: An International Perspective
Cross-linguistic studies offer critical insights into the neural and cognitive mechanisms underlying primary progressive aphasia (PPA). Despite the global linguistic diversity—with nearly 83% of the world's population speaking a language other than English as their first or second language—the majority of existing PPA research relies heavily on English-speaking cohorts. Approximately 72–74% of participants in studies of logopenic variant PPA (lvPPA) are monolingual English speakers, raising important questions about the generalizability of current findings to non-English populations.
Language typology—encompassing features such as orthographic transparency, lexical tone, and morphological complexity—significantly shapes how clinical manifestations of each PPA variant emerge across different linguistic contexts. For example, semantic variant PPA (svPPA) presents distinctly in Japanese, where selective impairment in reading kanji characters—logographic symbols requiring intact semantic representations—mirrors the surface dyslexia observed in English-speaking patients, who typically over-rely on phonological decoding and misread irregular words. Conversely, patients speaking Italian, a language with relatively transparent orthography, or Turkish, an agglutinative language, tend to exhibit fewer overt reading errors but prominent difficulties in morphosyntactic or lexical tasks.
Similarly, motor-speech and grammatical deficits characteristic of the non-fluent/agrammatic variant (nfvPPA) vary considerably with language typology. While English speakers frequently demonstrate apraxia of speech through distortions in consonant clusters (e.g., "strong" → "s-trong"), speakers of languages with simpler phonotactic structures but richer morphological systems, such as Italian or Chinese, tend to manifest subtler articulation errors but more pronounced deficits in grammatical inflection or classifier usage. These linguistic discrepancies highlight how each language's phonological and grammatical demands can reveal distinct aspects of underlying neural vulnerability.
To address the limitations imposed by linguistic biases, international collaborations have increasingly focused on adapting and validating PPA assessments for diverse languages. In 2019, our group launched the Chinese Language Assessment in PPA (CLAP) project, collaborating with researchers in Taiwan, Hong Kong, and the United States to enroll nearly 200 Chinese-speaking participants. Chinese, being a tonal language wherein tone conveys lexical meaning, provides unique diagnostic challenges and opportunities. For instance, nfvPPA patients tested with "tone twisters" showed disproportionately high rates of tone-substitution errors, correlating with atrophy in regions critical to motor speech planning—the left anterior insula and frontal operculum.
Further emphasizing the semantic networks involved in svPPA, Chinese noun classifiers (e.g., 把 [bǎ], 本 [běn], 堆 [duī]), which replace articles or plural markers commonly used in English, prove highly sensitive to anterior temporal lobe dysfunction. Patients with svPPA frequently struggle to select appropriate classifiers, highlighting the close relationship between classifier production and conceptual-semantic knowledge integrity. In Turkish, the agglutinative morphology poses distinct challenges in repetition tasks for lvPPA patients, who experience greater difficulty as syllable counts increase—contrasting English-speaking patients who typically find word-level complexity more challenging.
Collectively, these findings illustrate how language-specific features—ranging from logographic scripts and tonal systems to agglutinative morphology—can expose previously under-recognized facets of PPA symptomatology. Recognizing the profound implications of linguistic diversity for accurate diagnosis and effective treatment, our group and international collaborators have established the International Network for Cross-Linguistic Research on Brain Health (INCLUDE). This consortium, with members from over 20 countries, aims to develop standardized, culturally, and linguistically sensitive diagnostic tools and treatment strategies.
By pooling international data and harmonizing protocols across diverse languages, INCLUDE seeks to clarify how writing systems, lexical tones, and morphological structures may differentially mask or highlight core deficits across PPA variants. Such international efforts promise substantial benefits for patient communities worldwide, reducing diagnostic disparities and improving access to culturally tailored therapies. Moreover, cross-linguistic research enriches theoretical models of language networks by testing them across varied linguistic frameworks, ultimately advancing our understanding of how the human brain is organized for language and promoting global equity in diagnosis and care for individuals with PPA.

Conclusion
Over the past several decades, the study of primary progressive aphasia has changed our understanding of cognition and language. Initially viewed as an anomaly in the landscape of neurodegenerative diseases, PPA emerged as a powerful lens into how neural networks implement fundamental cognitive processes. Semantic variant cases uncovered the profound role of the anterior temporal lobes in conceptual knowledge, while logopenic patients exposed the posterior temporal-parietal phonological loop that is so often the target of atypical Alzheimer's pathology. The non-fluent/agrammatic variant revealed the delicate balance of motor planning, grammatical structuring, and executive control necessary for speech production. In each of these syndromes, we see how disease spreads predictably through large-scale connectivity networks, reaffirming that language is an intricate ensemble of interdependent sub-systems.
It has been our privilege to contribute to this evolving conversation through clinical research, patient care, cross-linguistic collaborations, and mentorship. The journey continues, with new challenges and exciting prospects on the horizon. As we refine models of PPA and expand available treatment options, our collective work is poised to benefit not only the relatively small number of patients with these rare syndromes, but also the broader scientific community seeking to understand how the human brain encodes, retrieves, and communicates knowledge. The enduring lesson is that by illuminating the most specialized and personal aspects of cognition—like the words we speak and the concepts they represent—we ultimately learn more about ourselves and our shared humanity.

"""





